[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }

urn = { workspace = true }
uuid = { workspace = true }

chrono = { workspace = true }

thiserror = { workspace = true }
anyhow = { workspace = true }

sqlx = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }

moka = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
replay-macros = { path = "../macros" }

log = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-test = { workspace = true }
testcontainers-modules = { workspace = true }
dotenvy = { workspace = true }
